# Generated by Django 2.2.1 on 2019-05-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dish_type', models.CharField(choices=[('DES', 'Dessert'), ('ENT', 'Entry'), ('SOP', 'Soup')], max_length=3)),
            ],
        ),
    ]
